### ISSUE TITLE
add Support for autopilot mod

### ISSUE THREAD

**Issue by hamsterofficial** [hq-af/hqOsu#1]
Hey,
You can add support for autopilot? Because when I turn on the autopilot, relax does not work at all. This is useful on private servers :)

Thanks.

**Comment by sl0zy** [comment]
agree, this hack needs support for autopilot

**Comment by Califboy1986** [comment]
Helo i have a sky VIPER 2450 gps drone.i was flying it and it was fully looked in gps mode and it lost contact with the controller and then started to take of i lost site of the drone then when i got contact with the drone i could see the camera feed and it was on the ground but could not find it.hope that there is a way to up load the data from the autopilot.

**Comment by hamsterofficial** [comment]
ADD THIS KURWA MAĆ :-: PLZ

**Comment by spook0** [comment]
fuck you

**Comment by hamsterofficial** [comment]
fuck you spook

**Comment by MarcPlaying** [comment]
agree

**Comment by hq-af** [comment]
added
