### ISSUE TITLE
everytime i run the hqOsu.exe this happens 

### ISSUE THREAD

**Issue by egenisvegan** [hq-af/hqOsu#26]
SUCCESS: The process "hqOsu.exe" with PID 32896 has been terminated.
ERROR: The process "osu!.exe" not found.
C:\Users\jeff\Desktop\new\_new\hqOsu.Loader.exe
        1 file(s) moved.

i have osu installed,i have the most stable version of osu, i have the latest version of hqOsu but everytine i run hqOsu.exe instead of it giveing me the option of finding and selecting my osu.exe it crashes and and deletes the hqOsu.Loader and whatever i do it has the same result and i also have reinstalled osu and also this multiple times but it always has the same result

**Comment by hq-af** [comment]
download the new .zip (it's antivirus related but should be fixed now)

**Comment by 3Nya3** [comment]
> chrome doesnt let me download

Could you specify what's happening? Are you receiving an error? Or you just can't download anything?

**Comment by egenisvegan** [comment]
alright this new update worked thx ;3
