### ISSUE TITLE
remove hitscan

### ISSUE THREAD

**Issue by spook0** [hq-af/hqOsu#3]
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan
remove hitscan

**Comment by hamsterofficial** [comment]
fuck you spook

**Comment by spook0** [comment]
i will literally murder your entire family

**Comment by hamsterofficial** [comment]
I ddos you 24/7
