### ISSUE TITLE
score submitting 

### ISSUE THREAD

**Issue by isiahah** [hq-af/hqOsu#45]
NOW THE SCORE SUBMITTING DONT WORK. 
"There was an error during timing calculations. If you continue to get this error, please update your AUDIO/SOUND CARD drivers! Your score will not be submitted for this play."

**Comment by Euer24** [comment]
yup  me  2

**Comment by Ougadougou77** [comment]
I cant even start the bot for me, it says unsupported osu! version but i have done the update

**Comment by isiahah** [comment]
> I cant even start the bot for me, it says unsupported osu! version but i have done the update

try to either reinstall the application or you can try to launch Hqosu.launcher.exe

**Comment by Ougadougou77** [comment]
i hace reinstalled osu, hqosu, lunched the the thing and it still not working... pls help hq-af

**Comment by Pinturillo** [comment]
i can't submit scores help

**Comment by isiahah** [comment]
> i can't submit scores help

we have the same problem. 
i think that hq-af is working on it!

**Comment by Pinturillo** [comment]
i hope so

**Comment by isiahah** [comment]
> i have reinstalled osu, hqosu, lunched the the thing and it still not working... pls help hq-af

have you remember to give the direction to osu!.exe?

**Comment by Ougadougou77** [comment]
> 
> 
> > i have reinstalled osu, hqosu, lunched the the thing and it still not working... pls help hq-af
> 
> have you remember to give the direction to osu!.exe?

Yes i think i've done everything.. That cannot be related to my hardware that must be a bug with the update everything were working fine before the update

**Comment by hq-af** [comment]
fixed :lul:
