### ISSUE TITLE
Can u help me? What is this? HOW FIX IT?

### ISSUE THREAD

**Issue by LeqiXx** [hq-af/hqOsu#7]
![default](https://user-images.githubusercontent.com/42035597/43584455-17747aae-966b-11e8-9491-722ac6facfee.png)

**Comment by cyanidee** [comment]
"could not load file or assembly ..." - self-explains itself lol

**Comment by LeqiXx** [comment]
cyanidee, how fix it?

**Comment by hq-af** [comment]
download from https://github.com/hq-af/hqOsu/releases/download/v1.5.0.0-beta/hqOsu-beta.zip
